spring:
  datasource:
    url: jdbc:mysql://localhost:3306/psy-consult-pro
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    banner-mode: "off"
mybatis:
  # mapper 路径
  mapperLocations: classpath:mapper/*.xml
  # 扫描实体类
  typeAliasesPackage: com.tom.model
server:
  port: 80
# 日志输出级别
#logging:
#  level:
#    root: warn
